version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "****"
      MINIO_OPTS: "--compat --cors-origin http://localhost:5012"
    volumes:
      - ./data:/data
    command: server /data --console-address :9001

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: "routeawaredb"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "****"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports: 
        - "5432:5432"

volumes:
    postgres-data: 